name: Docker Image CI

on:
  schedule:
    - cron: '0 15 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin    
    - name: Build
      run: ./build.sh "org.opencontainers.image.description=\"https://github.com/golden-containers/build-docker-ruby/actions/runs/${GITHUB_RUN_ID}\""
